# Generated by Django 2.0.6 on 2018-11-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
